### ISSUE TITLE
add mime_types

### ISSUE THREAD

**Issue by SillyCoyote** [atelierabbey/Skivvy#273]

**Comment by GrayofD4** [comment]
// REGISTER - MIME types
        // Added wp-upload MIME types  - https://www.sitepoint.com/web-foundations/mime-types-complete-list/
    function skivvy_add_custom_mime_types($mimes){
        return array_merge($mimes,array (
            'swf' => 'application/x-shockwave-flash',
            'eps' => 'application/postscript',
            'svg' => 'image/svg+xml'
        ));
    } add_filter('upload_mimes','skivvy_add_custom_mime_types');
